HyperParams = {
    "BUFFER_SIZE": 1_000,
    "BATCH_SIZE": 32,
    "GAMMA": 0.99,
    "LEARNING_RATE": 0.0003,
    "MAX_EPSILON": 1.0,
    "MIN_EPSILON": 0.01,
    "EPSILON_DECAY": 0.0001,
    "MAX_EPISODE": 2000,
    "TARGET_UPDATE_AFTER": 500,
    "TARGET_UPDATE_STEP": 20,
    "IS_LEARN": True,
    "IS_LOG": False,
    "IS_SAVE": True,
    "IS_LOAD": False,
}
